#!/bin/bash
# A script to do playerctl next if up is passed as a paremeter and playerctl previous if down is passed as a parameter
# This is a workaround for the fact that playerctl doesn't work with hyprland
# This script is used by the hyprland script player-control

direction=$1
if test "$direction" = "down"
then
	playerctl previous
elif test "$direction" = "up"
then
	playerctl next
fi