#!/usr/bin/bash

# cursor theme
hyprctl setcursor Catppuccin-Macchiato-Dark-Cursors 24

# bar
waybar &

# wallpaper
hyprpaper &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xhost +SI:localuser:root &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
