#!/usr/bin/bash

# cursor theme
hyprctl setcursor Catppuccin-Macchiato-Dark-Cursors 24

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
#waybar &

# eww
eww daemon &
eww open bar &


# wallpaper
hyprpaper &

# other
/usr/libexec/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
